Develop
MixDrinks/android pull request #10
Opened 2023-03-13 12:34 UTC by YuraDekhtiar

2023-03-13 16:17 UTC, VovaStelmashchuk requested changes

2023-03-13 16:17 UTC, VovaStelmashchuk commented on app/src/main/java/org/mixdrinks/mixdrinks/features/data/SettingsResponse.kt
> +//class SettingsResponse(
якщо сутність не потрібна просто видай її

2023-03-13 16:17 UTC, VovaStelmashchuk commented on app/src/main/java/org/mixdrinks/mixdrinks/features/filter/ui/FilterScreen.kt
> +    //val listCheckedFilter by viewModel.listCheckedFilter
Якщо щось не треба то просто видаляй

2023-03-13 16:18 UTC, VovaStelmashchuk commented on app/src/main/java/org/mixdrinks/mixdrinks/app/MainActivity.kt
> +            MixDrinksApp(modifier = Modifier)
Тут modifier теж забери

2023-03-13 17:56 UTC, YuraDekhtiar commented on app/src/main/java/org/mixdrinks/mixdrinks/features/filter/ui/FilterScreen.kt
> +    //val listCheckedFilter by viewModel.listCheckedFilter
це ще не готове, я не розібрався як ще реалізувати це і щоб не було сповіщень закоментував

2023-03-20 13:54 UTC, VovaStelmashchuk approved these changes

2023-03-20 13:54 UTC, merged